config/routes.rb
Rails.application.routes.draw do
  resources :cars_parts
  # route for cars search
  resources :cars do
    collection do
      get 'search'
    end
  end
  # route for makes search
  resources :makes do
    collection do
      get 'search'
    end
  end
  # route for parts search
  resources :parts do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cars_part.rb
class CarsPart < ApplicationRecord
  belongs_to :car
  belongs_to :part
end

app/controllers/cars_parts_controller.rb
class CarsPartsController < ApplicationController
  before_action :set_cars_part, only: [:show, :edit, :update, :destroy]

  # GET /cars_parts
  # GET /cars_parts.json
  def index
    @cars_parts = CarsPart.all
  end

  # GET /cars_parts/1
  # GET /cars_parts/1.json
  def show
  end

  # GET /cars_parts/new
  def new
    @cars_part = CarsPart.new
  end

  # GET /cars_parts/1/edit
  def edit
  end

  # POST /cars_parts
  # POST /cars_parts.json
  def create
    @cars_part = CarsPart.new(cars_part_params)

    respond_to do |format|
      if @cars_part.save
        format.html { redirect_to @cars_part, notice: 'Cars part was successfully created.' }
        format.json { render :show, status: :created, location: @cars_part }
      else
        format.html { render :new }
        format.json { render json: @cars_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars_parts/1
  # PATCH/PUT /cars_parts/1.json
  def update
    respond_to do |format|
      if @cars_part.update(cars_part_params)
        format.html { redirect_to @cars_part, notice: 'Cars part was successfully updated.' }
        format.json { render :show, status: :ok, location: @cars_part }
      else
        format.html { render :edit }
        format.json { render json: @cars_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars_parts/1
  # DELETE /cars_parts/1.json
  def destroy
    @cars_part.destroy
    respond_to do |format|
      format.html { redirect_to cars_parts_url, notice: 'Cars part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cars_part
      @cars_part = CarsPart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cars_part_params
      params.require(:cars_part).permit(:car_id, :part_id)
    end
end

app/helpers/cars_parts_helper.rb
module CarsPartsHelper
end

app/views/cars_parts/_form.html.erb
<%= form_with(model: cars_part, local: true) do |form| %>
  <% if cars_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cars_part.errors.count, "error") %> prohibited this cars_part from being saved:</h2>

      <ul>
      <% cars_part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.text_field :car_id %>
  </div>

  <div class="field">
    <%= form.label :part_id %>
    <%= form.text_field :part_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars_parts/edit.html.erb
<h1>Editing Cars Part</h1>

<%= render 'form', cars_part: @cars_part %>

<%= link_to 'Show', @cars_part %> |
<%= link_to 'Back', cars_parts_path %>

app/views/cars_parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars Parts</h1>

<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>Part</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars_parts.each do |cars_part| %>
      <tr>
        <td><%= cars_part.car %></td>
        <td><%= cars_part.part %></td>
        <td><%= link_to 'Show', cars_part %></td>
        <td><%= link_to 'Edit', edit_cars_part_path(cars_part) %></td>
        <td><%= link_to 'Destroy', cars_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cars Part', new_cars_part_path %>

app/views/cars_parts/new.html.erb
<h1>New Cars Part</h1>

<%= render 'form', cars_part: @cars_part %>

<%= link_to 'Back', cars_parts_path %>

app/views/cars_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car:</strong>
  <%= @cars_part.car %>
</p>

<p>
  <strong>Part:</strong>
  <%= @cars_part.part %>
</p>

<%= link_to 'Edit', edit_cars_part_path(@cars_part) %> |
<%= link_to 'Back', cars_parts_path %>